language: node_js
node_js:
  - "14"
  - "15"
  - "16"
services:
  - mongodb
before_install:
  - echo "replication:" | sudo tee -a /etc/mongodb.conf
  - echo -e "\treplSetName: travisReplica" | sudo tee -a /etc/mongodb.conf
  - sudo systemctl stop mongod
  - sleep 20
  - sudo systemctl start mongod
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15