language: node_js
node_js:
  - "14"
services:
  - mongodb
before_install:
  - cat /lib/systemd/system/mongod.service
  - sudo systemctl status mongod
  - echo "replication:" | sudo tee -a /etc/mongodb.conf
  - echo -n "  replSetName:" | sudo tee -a /etc/mongodb.conf
  - echo " replTravis" | sudo tee -a /etc/mongodb.conf
  - sudo cat /etc/mongodb.conf
  - sudo systemctl restart mongod
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sudo systemctl status mongod
  - sleep 15