language: node_js
node_js:
  - "14"
  - "15"
  - "16"
services:
  - mongodb
before_script:
  - echo "replSet = travisReplica" | sudo tee -a /etc/mongodb.conf
  - sudo /etc/init.d/mongodb restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15