language: node_js
jobs:
  include:
  - dist: focal
    node_js: '18'
  - node_js: '17'
  - node_js: '16'
  - node_js: '14'
services:
  - mongodb
before_install:
  - sudo systemctl stop mongod
  - sudo sed -i -e 's/mongod --config/mongod --replSet rs0 --config/g' /lib/systemd/system/mongod.service
  - sudo systemctl daemon-reload
  - sudo systemctl start mongod
  - sleep 15
  - mongo --eval 'rs.initiate()'
  - sleep 5