language: node_js
node_js:
  - "14"
services:
  - mongodb
before_install:
  - echo "[Service]" | sudo tee -a /lib/systemd/system/mongod.service
  - echo "ExecStart=/usr/bin/mongod --config /etc/mongod.conf --replSet rs0" | sudo tee -a /lib/systemd/system/mongod.service
  - cat /lib/systemd/system/mongod.service
  - sudo systemctl daemon-reload
  - sudo systemctl status mongod
  - sudo systemctl restart mongod
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sudo systemctl status mongod
  - sleep 15