language: node_js
node_js:
  - "14"
  - "15"
  - "16"
services:
  - mongodb
before_install:
  - sudo echo "replication:" >> /etc/mongodb.conf
  - sudo echo -e "\treplSetName: travisReplica" >> etc/mongodb.conf
  - sudo systemctl stop mongod
  - sleep 20
  - sudo systemctl start mongod
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15