language: node_js
node_js:
  - "14"
  - "15"
  - "16"
services:
  - mongodb
before_install:
  - echo "replication.replSetName = replTravis" | sudo tee -a /etc/mongodb.conf
  - sudo systemctl stop mongod
  - sleep 20
  - sudo systemctl start mongod
  - sleep 20
  - mongo --eval 'rs.reconfig({ _id:\ 'replTravis' })'
  - mongo --eval 'rs.initiate()'
  - sleep 15