language: node_js
node_js:
  - "14"
  - "16"
  - "17"
services:
  - mongodb
before_install:
  - sudo systemctl stop mongod
  - sudo sed -i -e 's/mongod --config/mongod --replSet rs0 --config/g' /lib/systemd/system/mongod.service
  - sudo systemctl daemon-reload
  - sudo systemctl start mongod
  - sleep 15
  - mongo --eval 'rs.initiate()'
  - sleep 5